name: jumperbreaker_flutter_application_test_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  logger: ^1.1.0
  intl: ^0.17.0
  connectivity_plus: ^3.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
      - family: Gilroy
        fonts:
          - asset: lib/fonts/Gilroy-ExtraBold.otf
          - asset: lib/fonts/Gilroy-Light.otf
          - asset: lib/fonts/Gilroy-Medium.ttf
          
             
